import "./globals.css";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className=' bg-gradient-to-tl from-slate-800 via-purple-800 to-slate-700 flex justify-center'>{children}</body>
    </html>
  );
}
